package com.juzhai.act.model;

import java.io.Serializable;
import java.util.Date;

public class ActCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_category.id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_category.act_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    private Long actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_category.category_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_category.create_time
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_act_category
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_category.id
     *
     * @return the value of tb_act_category.id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_category.id
     *
     * @param id the value for tb_act_category.id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_category.act_id
     *
     * @return the value of tb_act_category.act_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_category.act_id
     *
     * @param actId the value for tb_act_category.act_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_category.category_id
     *
     * @return the value of tb_act_category.category_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_category.category_id
     *
     * @param categoryId the value for tb_act_category.category_id
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_category.create_time
     *
     * @return the value of tb_act_category.create_time
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_category.create_time
     *
     * @param createTime the value for tb_act_category.create_time
     *
     * @mbggenerated Fri Oct 28 15:35:11 CST 2011
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}