package com.juzhai.act.model;

import java.io.Serializable;
import java.util.Date;

public class ActDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_detail.act_id
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private Long actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_detail.display
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private Boolean display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_detail.create_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_detail.last_modify_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_act_detail.detail
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_act_detail
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_detail.act_id
     *
     * @return the value of tb_act_detail.act_id
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_detail.act_id
     *
     * @param actId the value for tb_act_detail.act_id
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_detail.display
     *
     * @return the value of tb_act_detail.display
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_detail.display
     *
     * @param display the value for tb_act_detail.display
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_detail.create_time
     *
     * @return the value of tb_act_detail.create_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_detail.create_time
     *
     * @param createTime the value for tb_act_detail.create_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_detail.last_modify_time
     *
     * @return the value of tb_act_detail.last_modify_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_detail.last_modify_time
     *
     * @param lastModifyTime the value for tb_act_detail.last_modify_time
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_act_detail.detail
     *
     * @return the value of tb_act_detail.detail
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_act_detail.detail
     *
     * @param detail the value for tb_act_detail.detail
     *
     * @mbggenerated Wed Dec 21 14:57:35 CST 2011
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}