package com.juzhai.preference.mapper;

import com.juzhai.preference.model.UserPreference;
import com.juzhai.preference.model.UserPreferenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int countByExample(UserPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int deleteByExample(UserPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int insert(UserPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int insertSelective(UserPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    List<UserPreference> selectByExample(UserPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    UserPreference selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByExampleSelective(@Param("record") UserPreference record, @Param("example") UserPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByExample(@Param("record") UserPreference record, @Param("example") UserPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByPrimaryKeySelective(UserPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_preference
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByPrimaryKey(UserPreference record);
}