package com.juzhai.passport.mapper;

import com.juzhai.passport.model.Report;
import com.juzhai.passport.model.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    Report selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Thu Sep 06 12:25:23 CST 2012
     */
    int updateByPrimaryKey(Report record);
}