package com.juzhai.passport.model;

import java.io.Serializable;
import java.util.Date;

public class InterestUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interest_user.id
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interest_user.interest_uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private Long interestUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interest_user.uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interest_user.create_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interest_user.last_modify_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_interest_user
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interest_user.id
     *
     * @return the value of tb_interest_user.id
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interest_user.id
     *
     * @param id the value for tb_interest_user.id
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interest_user.interest_uid
     *
     * @return the value of tb_interest_user.interest_uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public Long getInterestUid() {
        return interestUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interest_user.interest_uid
     *
     * @param interestUid the value for tb_interest_user.interest_uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public void setInterestUid(Long interestUid) {
        this.interestUid = interestUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interest_user.uid
     *
     * @return the value of tb_interest_user.uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interest_user.uid
     *
     * @param uid the value for tb_interest_user.uid
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interest_user.create_time
     *
     * @return the value of tb_interest_user.create_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interest_user.create_time
     *
     * @param createTime the value for tb_interest_user.create_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interest_user.last_modify_time
     *
     * @return the value of tb_interest_user.last_modify_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interest_user.last_modify_time
     *
     * @param lastModifyTime the value for tb_interest_user.last_modify_time
     *
     * @mbggenerated Wed Dec 07 11:39:08 CST 2011
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}