package com.juzhai.home.model;

import java.io.Serializable;
import java.util.Date;

public class DialogContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.id
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.content
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.pic
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.sender_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private Long senderUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.receiver_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private Long receiverUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.create_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dialog_content.last_modify_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_dialog_content
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.id
     *
     * @return the value of tb_dialog_content.id
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.id
     *
     * @param id the value for tb_dialog_content.id
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.content
     *
     * @return the value of tb_dialog_content.content
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.content
     *
     * @param content the value for tb_dialog_content.content
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.pic
     *
     * @return the value of tb_dialog_content.pic
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.pic
     *
     * @param pic the value for tb_dialog_content.pic
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.sender_uid
     *
     * @return the value of tb_dialog_content.sender_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public Long getSenderUid() {
        return senderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.sender_uid
     *
     * @param senderUid the value for tb_dialog_content.sender_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setSenderUid(Long senderUid) {
        this.senderUid = senderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.receiver_uid
     *
     * @return the value of tb_dialog_content.receiver_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public Long getReceiverUid() {
        return receiverUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.receiver_uid
     *
     * @param receiverUid the value for tb_dialog_content.receiver_uid
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setReceiverUid(Long receiverUid) {
        this.receiverUid = receiverUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.create_time
     *
     * @return the value of tb_dialog_content.create_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.create_time
     *
     * @param createTime the value for tb_dialog_content.create_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dialog_content.last_modify_time
     *
     * @return the value of tb_dialog_content.last_modify_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dialog_content.last_modify_time
     *
     * @param lastModifyTime the value for tb_dialog_content.last_modify_time
     *
     * @mbggenerated Wed Jul 18 18:07:34 CST 2012
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}