package com.juzhai.antiad.mapper;

import com.juzhai.antiad.model.AdLockIp;
import com.juzhai.antiad.model.AdLockIpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdLockIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int countByExample(AdLockIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int deleteByExample(AdLockIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int insert(AdLockIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int insertSelective(AdLockIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    List<AdLockIp> selectByExample(AdLockIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    AdLockIp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByExampleSelective(@Param("record") AdLockIp record, @Param("example") AdLockIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByExample(@Param("record") AdLockIp record, @Param("example") AdLockIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByPrimaryKeySelective(AdLockIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    int updateByPrimaryKey(AdLockIp record);
}