package com.juzhai.act.model;

import java.io.Serializable;

public class Question implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.id
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.type
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.name
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.answer
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.invite_text
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private String inviteText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_question.invite_word
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private String inviteWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_question
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.id
     *
     * @return the value of tb_question.id
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.id
     *
     * @param id the value for tb_question.id
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.type
     *
     * @return the value of tb_question.type
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.type
     *
     * @param type the value for tb_question.type
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.name
     *
     * @return the value of tb_question.name
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.name
     *
     * @param name the value for tb_question.name
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.answer
     *
     * @return the value of tb_question.answer
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.answer
     *
     * @param answer the value for tb_question.answer
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.invite_text
     *
     * @return the value of tb_question.invite_text
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public String getInviteText() {
        return inviteText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.invite_text
     *
     * @param inviteText the value for tb_question.invite_text
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setInviteText(String inviteText) {
        this.inviteText = inviteText == null ? null : inviteText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_question.invite_word
     *
     * @return the value of tb_question.invite_word
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public String getInviteWord() {
        return inviteWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_question.invite_word
     *
     * @param inviteWord the value for tb_question.invite_word
     *
     * @mbggenerated Mon Oct 03 14:17:40 CST 2011
     */
    public void setInviteWord(String inviteWord) {
        this.inviteWord = inviteWord == null ? null : inviteWord.trim();
    }
}