package com.juzhai.act.mapper;

import com.juzhai.act.model.RandomAct;
import com.juzhai.act.model.RandomActExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RandomActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int countByExample(RandomActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int deleteByExample(RandomActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int insert(RandomAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int insertSelective(RandomAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    List<RandomAct> selectByExample(RandomActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int updateByExampleSelective(@Param("record") RandomAct record, @Param("example") RandomActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_random_act
     *
     * @mbggenerated Mon Aug 22 23:11:38 CST 2011
     */
    int updateByExample(@Param("record") RandomAct record, @Param("example") RandomActExample example);
}