package com.juzhai.act.mapper;

import com.juzhai.act.model.SynonymAct;
import com.juzhai.act.model.SynonymActExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SynonymActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int countByExample(SynonymActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int deleteByExample(SynonymActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int insert(SynonymAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int insertSelective(SynonymAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    List<SynonymAct> selectByExample(SynonymActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    SynonymAct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int updateByExampleSelective(@Param("record") SynonymAct record, @Param("example") SynonymActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int updateByExample(@Param("record") SynonymAct record, @Param("example") SynonymActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int updateByPrimaryKeySelective(SynonymAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_synonym_act
     *
     * @mbggenerated Wed Nov 09 22:21:31 CST 2011
     */
    int updateByPrimaryKey(SynonymAct record);
}