package com.juzhai.act.mapper;

import com.juzhai.act.model.ActDetail;
import com.juzhai.act.model.ActDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int countByExample(ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int deleteByExample(ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int deleteByPrimaryKey(Long actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int insert(ActDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int insertSelective(ActDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    List<ActDetail> selectByExampleWithBLOBs(ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    List<ActDetail> selectByExample(ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    ActDetail selectByPrimaryKey(Long actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByExampleSelective(@Param("record") ActDetail record, @Param("example") ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") ActDetail record, @Param("example") ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByExample(@Param("record") ActDetail record, @Param("example") ActDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByPrimaryKeySelective(ActDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(ActDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_act_detail
     *
     * @mbggenerated Sat Dec 10 13:46:49 CST 2011
     */
    int updateByPrimaryKey(ActDetail record);
}