package com.juzhai.act.mapper;

import com.juzhai.act.model.HotAct;
import com.juzhai.act.model.HotActExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int countByExample(HotActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int deleteByExample(HotActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int insert(HotAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int insertSelective(HotAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    List<HotAct> selectByExample(HotActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int updateByExampleSelective(@Param("record") HotAct record, @Param("example") HotActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hot_act
     *
     * @mbggenerated Fri Aug 26 15:40:27 CST 2011
     */
    int updateByExample(@Param("record") HotAct record, @Param("example") HotActExample example);
}