package com.juzhai.act.mapper;

import com.juzhai.act.model.UserAct;
import com.juzhai.act.model.UserActExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int countByExample(UserActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int deleteByExample(UserActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int insert(UserAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int insertSelective(UserAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    List<UserAct> selectByExample(UserActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    UserAct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByExampleSelective(@Param("record") UserAct record, @Param("example") UserActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByExample(@Param("record") UserAct record, @Param("example") UserActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByPrimaryKeySelective(UserAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_act
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByPrimaryKey(UserAct record);
}