package com.juzhai.passport.mapper;

import com.juzhai.passport.model.Province;
import com.juzhai.passport.model.ProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    Province selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Aug 20 00:08:16 CST 2011
     */
    int updateByPrimaryKey(Province record);
}