package com.juzhai.passport.mapper;

import com.juzhai.passport.model.TpUser;
import com.juzhai.passport.model.TpUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int countByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int deleteByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int insert(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int insertSelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    List<TpUser> selectByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    TpUser selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByExampleSelective(@Param("record") TpUser record, @Param("example") TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByExample(@Param("record") TpUser record, @Param("example") TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByPrimaryKeySelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Mon Aug 15 00:11:16 CST 2011
     */
    int updateByPrimaryKey(TpUser record);
}