package com.juzhai.cms.mapper;

import com.juzhai.cms.model.AdSource;
import com.juzhai.cms.model.AdSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int countByExample(AdSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int deleteByExample(AdSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int insert(AdSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int insertSelective(AdSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    List<AdSource> selectByExample(AdSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    AdSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int updateByExampleSelective(@Param("record") AdSource record, @Param("example") AdSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int updateByExample(@Param("record") AdSource record, @Param("example") AdSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int updateByPrimaryKeySelective(AdSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad_source
     *
     * @mbggenerated Tue Jan 03 01:14:51 CST 2012
     */
    int updateByPrimaryKey(AdSource record);
}