package com.juzhai.post.model;

import java.io.Serializable;
import java.util.Date;

public class IdeaInterest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idea_interest.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idea_interest.idea_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long ideaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idea_interest.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idea_interest.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idea_interest.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_idea_interest
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idea_interest.id
     *
     * @return the value of tb_idea_interest.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idea_interest.id
     *
     * @param id the value for tb_idea_interest.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idea_interest.idea_id
     *
     * @return the value of tb_idea_interest.idea_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getIdeaId() {
        return ideaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idea_interest.idea_id
     *
     * @param ideaId the value for tb_idea_interest.idea_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setIdeaId(Long ideaId) {
        this.ideaId = ideaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idea_interest.uid
     *
     * @return the value of tb_idea_interest.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idea_interest.uid
     *
     * @param uid the value for tb_idea_interest.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idea_interest.create_time
     *
     * @return the value of tb_idea_interest.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idea_interest.create_time
     *
     * @param createTime the value for tb_idea_interest.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idea_interest.last_modify_time
     *
     * @return the value of tb_idea_interest.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idea_interest.last_modify_time
     *
     * @param lastModifyTime the value for tb_idea_interest.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}