package com.juzhai.post.model;

import java.io.Serializable;
import java.util.Date;

public class PostWindow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.post_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.purpose_type
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer purposeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.content
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.sequence
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post_window.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_post_window
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.id
     *
     * @return the value of tb_post_window.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.id
     *
     * @param id the value for tb_post_window.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.post_id
     *
     * @return the value of tb_post_window.post_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.post_id
     *
     * @param postId the value for tb_post_window.post_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.uid
     *
     * @return the value of tb_post_window.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.uid
     *
     * @param uid the value for tb_post_window.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.purpose_type
     *
     * @return the value of tb_post_window.purpose_type
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getPurposeType() {
        return purposeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.purpose_type
     *
     * @param purposeType the value for tb_post_window.purpose_type
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setPurposeType(Integer purposeType) {
        this.purposeType = purposeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.content
     *
     * @return the value of tb_post_window.content
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.content
     *
     * @param content the value for tb_post_window.content
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.sequence
     *
     * @return the value of tb_post_window.sequence
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.sequence
     *
     * @param sequence the value for tb_post_window.sequence
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.create_time
     *
     * @return the value of tb_post_window.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.create_time
     *
     * @param createTime the value for tb_post_window.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post_window.last_modify_time
     *
     * @return the value of tb_post_window.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post_window.last_modify_time
     *
     * @param lastModifyTime the value for tb_post_window.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}