package com.juzhai.passport.model;

import java.io.Serializable;
import java.util.Date;

public class Profile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.uid
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.has_modify_nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Boolean hasModifyNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String logoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.country
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.province
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.city
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.town
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.has_modify_gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Boolean hasModifyGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.birth_year
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.birth_month
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer birthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.birth_day
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.birth_secret
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Boolean birthSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.qq
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.msn
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.sub_email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Boolean subEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.weibo
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.blog
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String blog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.telephone
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.mobile
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.finish_school
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String finishSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.finish_subject
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String finishSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.company
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.profession_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.profession
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.constellation_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Long constellationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.nature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String nature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.address
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.home
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String home;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.height
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.shape
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String shape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.feature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.blood_type
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.education
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.house
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String house;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.car
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String car;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.min_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer minMonthlyIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.max_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer maxMonthlyIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.new_logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private String newLogoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.logo_verify_state
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Integer logoVerifyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.create_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.last_modify_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.last_update_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.last_web_login_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Date lastWebLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_profile.last_user_online_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private Date lastUserOnlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_profile
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.uid
     *
     * @return the value of tb_profile.uid
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.uid
     *
     * @param uid the value for tb_profile.uid
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.nickname
     *
     * @return the value of tb_profile.nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.nickname
     *
     * @param nickname the value for tb_profile.nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.has_modify_nickname
     *
     * @return the value of tb_profile.has_modify_nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Boolean getHasModifyNickname() {
        return hasModifyNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.has_modify_nickname
     *
     * @param hasModifyNickname the value for tb_profile.has_modify_nickname
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setHasModifyNickname(Boolean hasModifyNickname) {
        this.hasModifyNickname = hasModifyNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.logo_pic
     *
     * @return the value of tb_profile.logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getLogoPic() {
        return logoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.logo_pic
     *
     * @param logoPic the value for tb_profile.logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLogoPic(String logoPic) {
        this.logoPic = logoPic == null ? null : logoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.country
     *
     * @return the value of tb_profile.country
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.country
     *
     * @param country the value for tb_profile.country
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setCountry(Long country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.province
     *
     * @return the value of tb_profile.province
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.province
     *
     * @param province the value for tb_profile.province
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setProvince(Long province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.city
     *
     * @return the value of tb_profile.city
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.city
     *
     * @param city the value for tb_profile.city
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setCity(Long city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.town
     *
     * @return the value of tb_profile.town
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.town
     *
     * @param town the value for tb_profile.town
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setTown(Long town) {
        this.town = town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.gender
     *
     * @return the value of tb_profile.gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.gender
     *
     * @param gender the value for tb_profile.gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.has_modify_gender
     *
     * @return the value of tb_profile.has_modify_gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Boolean getHasModifyGender() {
        return hasModifyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.has_modify_gender
     *
     * @param hasModifyGender the value for tb_profile.has_modify_gender
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setHasModifyGender(Boolean hasModifyGender) {
        this.hasModifyGender = hasModifyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.birth_year
     *
     * @return the value of tb_profile.birth_year
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.birth_year
     *
     * @param birthYear the value for tb_profile.birth_year
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.birth_month
     *
     * @return the value of tb_profile.birth_month
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getBirthMonth() {
        return birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.birth_month
     *
     * @param birthMonth the value for tb_profile.birth_month
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBirthMonth(Integer birthMonth) {
        this.birthMonth = birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.birth_day
     *
     * @return the value of tb_profile.birth_day
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.birth_day
     *
     * @param birthDay the value for tb_profile.birth_day
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBirthDay(Integer birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.birth_secret
     *
     * @return the value of tb_profile.birth_secret
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Boolean getBirthSecret() {
        return birthSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.birth_secret
     *
     * @param birthSecret the value for tb_profile.birth_secret
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBirthSecret(Boolean birthSecret) {
        this.birthSecret = birthSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.qq
     *
     * @return the value of tb_profile.qq
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.qq
     *
     * @param qq the value for tb_profile.qq
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.msn
     *
     * @return the value of tb_profile.msn
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.msn
     *
     * @param msn the value for tb_profile.msn
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.email
     *
     * @return the value of tb_profile.email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.email
     *
     * @param email the value for tb_profile.email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.sub_email
     *
     * @return the value of tb_profile.sub_email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Boolean getSubEmail() {
        return subEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.sub_email
     *
     * @param subEmail the value for tb_profile.sub_email
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setSubEmail(Boolean subEmail) {
        this.subEmail = subEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.weibo
     *
     * @return the value of tb_profile.weibo
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.weibo
     *
     * @param weibo the value for tb_profile.weibo
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.blog
     *
     * @return the value of tb_profile.blog
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.blog
     *
     * @param blog the value for tb_profile.blog
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.telephone
     *
     * @return the value of tb_profile.telephone
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.telephone
     *
     * @param telephone the value for tb_profile.telephone
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.mobile
     *
     * @return the value of tb_profile.mobile
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.mobile
     *
     * @param mobile the value for tb_profile.mobile
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.finish_school
     *
     * @return the value of tb_profile.finish_school
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getFinishSchool() {
        return finishSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.finish_school
     *
     * @param finishSchool the value for tb_profile.finish_school
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setFinishSchool(String finishSchool) {
        this.finishSchool = finishSchool == null ? null : finishSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.finish_subject
     *
     * @return the value of tb_profile.finish_subject
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getFinishSubject() {
        return finishSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.finish_subject
     *
     * @param finishSubject the value for tb_profile.finish_subject
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setFinishSubject(String finishSubject) {
        this.finishSubject = finishSubject == null ? null : finishSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.company
     *
     * @return the value of tb_profile.company
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.company
     *
     * @param company the value for tb_profile.company
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.profession_id
     *
     * @return the value of tb_profile.profession_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.profession_id
     *
     * @param professionId the value for tb_profile.profession_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setProfessionId(Long professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.profession
     *
     * @return the value of tb_profile.profession
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.profession
     *
     * @param profession the value for tb_profile.profession
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.constellation_id
     *
     * @return the value of tb_profile.constellation_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Long getConstellationId() {
        return constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.constellation_id
     *
     * @param constellationId the value for tb_profile.constellation_id
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setConstellationId(Long constellationId) {
        this.constellationId = constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.nature
     *
     * @return the value of tb_profile.nature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.nature
     *
     * @param nature the value for tb_profile.nature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.address
     *
     * @return the value of tb_profile.address
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.address
     *
     * @param address the value for tb_profile.address
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.home
     *
     * @return the value of tb_profile.home
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.home
     *
     * @param home the value for tb_profile.home
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setHome(String home) {
        this.home = home == null ? null : home.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.height
     *
     * @return the value of tb_profile.height
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.height
     *
     * @param height the value for tb_profile.height
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.shape
     *
     * @return the value of tb_profile.shape
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.shape
     *
     * @param shape the value for tb_profile.shape
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.feature
     *
     * @return the value of tb_profile.feature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.feature
     *
     * @param feature the value for tb_profile.feature
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.blood_type
     *
     * @return the value of tb_profile.blood_type
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.blood_type
     *
     * @param bloodType the value for tb_profile.blood_type
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.education
     *
     * @return the value of tb_profile.education
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.education
     *
     * @param education the value for tb_profile.education
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.house
     *
     * @return the value of tb_profile.house
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.house
     *
     * @param house the value for tb_profile.house
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setHouse(String house) {
        this.house = house == null ? null : house.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.car
     *
     * @return the value of tb_profile.car
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.car
     *
     * @param car the value for tb_profile.car
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.min_monthly_income
     *
     * @return the value of tb_profile.min_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getMinMonthlyIncome() {
        return minMonthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.min_monthly_income
     *
     * @param minMonthlyIncome the value for tb_profile.min_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setMinMonthlyIncome(Integer minMonthlyIncome) {
        this.minMonthlyIncome = minMonthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.max_monthly_income
     *
     * @return the value of tb_profile.max_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getMaxMonthlyIncome() {
        return maxMonthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.max_monthly_income
     *
     * @param maxMonthlyIncome the value for tb_profile.max_monthly_income
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setMaxMonthlyIncome(Integer maxMonthlyIncome) {
        this.maxMonthlyIncome = maxMonthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.new_logo_pic
     *
     * @return the value of tb_profile.new_logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public String getNewLogoPic() {
        return newLogoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.new_logo_pic
     *
     * @param newLogoPic the value for tb_profile.new_logo_pic
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setNewLogoPic(String newLogoPic) {
        this.newLogoPic = newLogoPic == null ? null : newLogoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.logo_verify_state
     *
     * @return the value of tb_profile.logo_verify_state
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Integer getLogoVerifyState() {
        return logoVerifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.logo_verify_state
     *
     * @param logoVerifyState the value for tb_profile.logo_verify_state
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLogoVerifyState(Integer logoVerifyState) {
        this.logoVerifyState = logoVerifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.create_time
     *
     * @return the value of tb_profile.create_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.create_time
     *
     * @param createTime the value for tb_profile.create_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.last_modify_time
     *
     * @return the value of tb_profile.last_modify_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.last_modify_time
     *
     * @param lastModifyTime the value for tb_profile.last_modify_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.last_update_time
     *
     * @return the value of tb_profile.last_update_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.last_update_time
     *
     * @param lastUpdateTime the value for tb_profile.last_update_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.last_web_login_time
     *
     * @return the value of tb_profile.last_web_login_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Date getLastWebLoginTime() {
        return lastWebLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.last_web_login_time
     *
     * @param lastWebLoginTime the value for tb_profile.last_web_login_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLastWebLoginTime(Date lastWebLoginTime) {
        this.lastWebLoginTime = lastWebLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_profile.last_user_online_time
     *
     * @return the value of tb_profile.last_user_online_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public Date getLastUserOnlineTime() {
        return lastUserOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_profile.last_user_online_time
     *
     * @param lastUserOnlineTime the value for tb_profile.last_user_online_time
     *
     * @mbggenerated Thu Aug 09 15:39:48 CST 2012
     */
    public void setLastUserOnlineTime(Date lastUserOnlineTime) {
        this.lastUserOnlineTime = lastUserOnlineTime;
    }
}