package com.juzhai.passport.model;

import java.io.Serializable;

public class Constellation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.name
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.start_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer startMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.start_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.end_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer endMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_constellation.end_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_constellation
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.id
     *
     * @return the value of tb_constellation.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.id
     *
     * @param id the value for tb_constellation.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.name
     *
     * @return the value of tb_constellation.name
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.name
     *
     * @param name the value for tb_constellation.name
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.start_month
     *
     * @return the value of tb_constellation.start_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getStartMonth() {
        return startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.start_month
     *
     * @param startMonth the value for tb_constellation.start_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setStartMonth(Integer startMonth) {
        this.startMonth = startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.start_date
     *
     * @return the value of tb_constellation.start_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.start_date
     *
     * @param startDate the value for tb_constellation.start_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setStartDate(Integer startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.end_month
     *
     * @return the value of tb_constellation.end_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getEndMonth() {
        return endMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.end_month
     *
     * @param endMonth the value for tb_constellation.end_month
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setEndMonth(Integer endMonth) {
        this.endMonth = endMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_constellation.end_date
     *
     * @return the value of tb_constellation.end_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_constellation.end_date
     *
     * @param endDate the value for tb_constellation.end_date
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setEndDate(Integer endDate) {
        this.endDate = endDate;
    }
}