package com.juzhai.passport.model;

import java.io.Serializable;
import java.util.Date;

public class TpUserAuth implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.tp_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long tpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.auth_info
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private String authInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tp_user_auth.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_tp_user_auth
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.id
     *
     * @return the value of tb_tp_user_auth.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.id
     *
     * @param id the value for tb_tp_user_auth.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.uid
     *
     * @return the value of tb_tp_user_auth.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.uid
     *
     * @param uid the value for tb_tp_user_auth.uid
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.tp_id
     *
     * @return the value of tb_tp_user_auth.tp_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.tp_id
     *
     * @param tpId the value for tb_tp_user_auth.tp_id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setTpId(Long tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.auth_info
     *
     * @return the value of tb_tp_user_auth.auth_info
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public String getAuthInfo() {
        return authInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.auth_info
     *
     * @param authInfo the value for tb_tp_user_auth.auth_info
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setAuthInfo(String authInfo) {
        this.authInfo = authInfo == null ? null : authInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.create_time
     *
     * @return the value of tb_tp_user_auth.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.create_time
     *
     * @param createTime the value for tb_tp_user_auth.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tp_user_auth.last_modify_time
     *
     * @return the value of tb_tp_user_auth.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tp_user_auth.last_modify_time
     *
     * @param lastModifyTime the value for tb_tp_user_auth.last_modify_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}