package com.juzhai.antiad.model;

import java.io.Serializable;
import java.util.Date;

public class AdLockIp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad_lock_ip.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad_lock_ip.ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad_lock_ip.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ad_lock_ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad_lock_ip.id
     *
     * @return the value of tb_ad_lock_ip.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad_lock_ip.id
     *
     * @param id the value for tb_ad_lock_ip.id
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad_lock_ip.ip
     *
     * @return the value of tb_ad_lock_ip.ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad_lock_ip.ip
     *
     * @param ip the value for tb_ad_lock_ip.ip
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad_lock_ip.create_time
     *
     * @return the value of tb_ad_lock_ip.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad_lock_ip.create_time
     *
     * @param createTime the value for tb_ad_lock_ip.create_time
     *
     * @mbggenerated Mon Sep 03 15:05:46 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}